language:
  - cpp

branches:
  only:
    - development
    - modules

notifications:
  email:
    on_success: never
    on_fail: always

git:
  depth: 1

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: osx
      osx_image: xcode8

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir install
  - ./easy_build.sh $PWD/install
  - cd build && make install && cd ..
  - export PATH="$PWD/install/bin:$PATH"
  - External/bats/bin/bats Test