site_name: QUIT
docs_dir: Docs
theme: mkdocs
# pages:
#     - Home: index.md
#     - About: about.md

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math