language:
  - cpp

notifications:
  email:
    on_success: never
    on_fail: always

git:
  depth: 1

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler:
        - gcc
      addons:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
          - g++-6
          - cmake
      before_script:
        - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
        - export CC=/usr/bin/gcc-6
        - export CXX=/usr/bin/g++-6
        - gcc -v && g++ -v && cmake --version
    - os: osx
      env: TARGET=mac

before_install:
  - git submodule update --init

script:
  - ./easy_build.sh
  - External/bats/bin/bats Test